"""empty message

Revision ID: 15381ebf6fe9
Revises: c09253ee92b3
Create Date: 2016-02-23 18:43:10.549685

"""

# revision identifiers, used by Alembic.
revision = '15381ebf6fe9'
down_revision = 'c09253ee92b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'content')
    ### end Alembic commands ###
