"""empty message

Revision ID: 45b66ec5b775
Revises: c2767500774b
Create Date: 2016-02-20 15:57:11.042629

"""

# revision identifiers, used by Alembic.
revision = '45b66ec5b775'
down_revision = 'c2767500774b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('store', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'store')
    ### end Alembic commands ###
