"""empty message

Revision ID: 6b8c059e47c2
Revises: None
Create Date: 2016-02-25 21:48:34.027395

"""

# revision identifiers, used by Alembic.
revision = '6b8c059e47c2'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tags')
    op.create_unique_constraint(None, 'tags', ['name'])
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me')
    op.drop_constraint(None, 'tags', type_='unique')
    op.add_column('posts', sa.Column('tags', mysql.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###
