"""empty message

Revision ID: 799224d68678
Revises: None
Create Date: 2016-02-20 15:39:40.382289

"""

# revision identifiers, used by Alembic.
revision = '799224d68678'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('classification_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'classification', ['classification_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'classification_id')
    ### end Alembic commands ###
