"""empty message

Revision ID: c2767500774b
Revises: 799224d68678
Create Date: 2016-02-20 15:53:52.220896

"""

# revision identifiers, used by Alembic.
revision = 'c2767500774b'
down_revision = '799224d68678'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=64), nullable=True))
    op.drop_column('posts', 'categories')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('categories', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('posts', 'category')
    ### end Alembic commands ###
