"""empty message

Revision ID: c85d17844e4f
Revises: None
Create Date: 2016-02-23 20:25:30.489042

"""

# revision identifiers, used by Alembic.
revision = 'c85d17844e4f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'content')
    ### end Alembic commands ###
